In [1]:
import numpy as np

In [2]:
A = np.array([[2, 3], [2, 1]])
e1 = np.array([1, 0])
e2 = np.array([0, 1])

In [4]:
# Finding Eigenvalues and Eigenvectors in Python
A_eig = np.linalg.eig(A)

print("\n")

print(f"Matrix A:\n{A} \n\nEigenvalues of matrix A:\n{A_eig[0]}\n\nEigenvectors of matrix A:\n{A_eig[1]}")



Matrix A:
[[2 3]
 [2 1]] 

Eigenvalues of matrix A:
[ 4. -1.]

Eigenvectors of matrix A:
[[ 0.83205029 -0.70710678]
 [ 0.5547002   0.70710678]]


In [5]:
# first eigenvector
A_eig[1][:, 0]

array([0.83205029, 0.5547002 ])

In [6]:
# second eigenvector
A_eig[1][:, 1]

array([-0.70710678,  0.70710678])