In [1]:
import numpy as np

In [2]:
P = np.array([ 
    
    [0, 0.75, 0.35, 0.25, 0.85], 
    [0.15, 0, 0.35, 0.25, 0.05], 
    [0.15, 0.15, 0, 0.25, 0.05], 
    [0.15, 0.05, 0.05, 0, 0.05], 
    [0.55, 0.05, 0.25, 0.25, 0]  
]) 

In [3]:
X0 = np.array([[0],[0],[0],[1],[0]])

In [5]:
X1 = np.matmul(P, X0)
print(X1)

[[0.25]
 [0.25]
 [0.25]
 [0.  ]
 [0.25]]


In [6]:
eigenvals, eigenvecs = np.linalg.eig(P)
eigenvals

array([ 1.        , -0.70367062,  0.00539505, -0.08267227, -0.21905217])

In [7]:
eigenvecs

array([[-0.76088562, -0.81362074,  0.10935376,  0.14270615, -0.39408574],
       [-0.25879453,  0.050269  , -0.6653158 ,  0.67528802, -0.66465044],
       [-0.2204546 ,  0.07869601, -0.29090665,  0.17007443,  0.35048734],
       [-0.1644783 ,  0.12446953,  0.19740707, -0.43678067,  0.23311487],
       [-0.52766004,  0.56018621,  0.64946163, -0.55128793,  0.47513398]])

In [11]:
sum(np.array([ 1.,-0.70367062, 0.00539505, -0.08267227, -0.21905217]))

np.float64(-9.999999994736442e-09)

In [10]:
sum(np.array([1, 2, 3]))

np.int64(6)