In [1]:
import numpy as np

In [4]:
A = np.array([
    [0, 2, 1],
    [1, 1, 1],
    [1, 2, 1]
], dtype=float)
A

array([[0., 2., 1.],
       [1., 1., 1.],
       [1., 2., 1.]])

In [9]:
B = np.array([[3], [6], [12]], dtype=float)
B

array([[ 3.],
       [ 6.],
       [12.]])

In [10]:
M = np.hstack((A, B))
M

array([[ 0.,  2.,  1.,  3.],
       [ 1.,  1.,  1.,  6.],
       [ 1.,  2.,  1., 12.]])

In [20]:
M[0]

array([0., 2., 1., 3.])